//! Query decomposition for domain-aware retrieval
//!
//! Breaks a user's natural-language query into multiple semantically richer
//! sub-queries aligned to the domain vocabulary of the target table.
//!
//! For domain-specific corpora (e.g. insurance policies), users often write
//! queries that have no BM25 keyword overlap with the actual document content.
//! Decomposition bridges that gap by generating alternative phrasings using
//! terminology extracted from the table's description and `domain_vocab` metadata.

use serde::{Deserialize, Serialize};

/// Domain context derived from a `Table` record.
///
/// Built from `Table.description` and `Table.metadata["domain_vocab"]`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DomainContext {
    /// Display name of the table
    pub table_name: String,
    /// Optional free-text description set at table creation time
    pub description: Option<String>,
    /// Known domain terms/jargon (from `Table.metadata["domain_vocab"]`).
    /// Populated either manually or auto-extracted during ingestion.
    pub vocab_hints: Vec<String>,
}

/// A single alternative search query generated by the decomposer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubQuery {
    /// The expanded / rephrased search query text
    pub text: String,
    /// LLM's rationale for generating this phrasing
    pub rationale: String,
}

/// The result of decomposing a user query.
#[derive(Debug, Clone)]
pub struct DecomposedQuery {
    /// The original user query (always included as sub-queries[0])
    pub original: String,
    /// All sub-queries including the original
    pub sub_queries: Vec<SubQuery>,
    /// The domain context that was used (if any)
    pub domain_context: Option<DomainContext>,
}

impl DecomposedQuery {
    /// Returns just the query texts as a Vec<String>.
    pub fn query_texts(&self) -> Vec<String> {
        self.sub_queries.iter().map(|s| s.text.clone()).collect()
    }

    /// True if no actual decomposition occurred (only the original query).
    pub fn is_passthrough(&self) -> bool {
        self.sub_queries.len() == 1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_domain_context_vocab_hints() {
        let ctx = DomainContext {
            table_name: "Insurance Policies".to_string(),
            description: Some("Life insurance product disclosure statements".to_string()),
            vocab_hints: vec![
                "TPD".to_string(),
                "PDS".to_string(),
                "waiting period".to_string(),
            ],
        };

        assert_eq!(ctx.table_name, "Insurance Policies");
        assert_eq!(ctx.vocab_hints.len(), 3);
        assert!(ctx.vocab_hints.contains(&"TPD".to_string()));
        assert!(ctx.vocab_hints.contains(&"waiting period".to_string()));
        assert_eq!(
            ctx.description.as_deref(),
            Some("Life insurance product disclosure statements")
        );
    }

    #[test]
    fn test_domain_context_default_empty_vocab() {
        let ctx = DomainContext {
            table_name: "General".to_string(),
            description: None,
            vocab_hints: vec![],
        };

        assert!(ctx.vocab_hints.is_empty());
        assert!(ctx.description.is_none());
    }

    #[test]
    fn test_sub_query_fields() {
        let sq = SubQuery {
            text: "total permanent disability benefit amount".to_string(),
            rationale: "user query mentions disability coverage; TPD is the domain term"
                .to_string(),
        };

        assert_eq!(sq.text, "total permanent disability benefit amount");
        assert!(sq.rationale.contains("TPD"));
    }

    #[test]
    fn test_decomposed_query_texts() {
        let dq = DecomposedQuery {
            original: "disability cover".to_string(),
            sub_queries: vec![
                SubQuery {
                    text: "disability cover".to_string(),
                    rationale: "original".to_string(),
                },
                SubQuery {
                    text: "TPD benefit".to_string(),
                    rationale: "domain term".to_string(),
                },
                SubQuery {
                    text: "total permanent disability".to_string(),
                    rationale: "expanded".to_string(),
                },
            ],
            domain_context: None,
        };

        let texts = dq.query_texts();
        assert_eq!(texts.len(), 3);
        assert_eq!(texts[0], "disability cover");
        assert_eq!(texts[1], "TPD benefit");
        assert!(!dq.is_passthrough());
    }

    #[test]
    fn test_decomposed_query_is_passthrough() {
        let dq = DecomposedQuery {
            original: "what is covered".to_string(),
            sub_queries: vec![SubQuery {
                text: "what is covered".to_string(),
                rationale: "passthrough".to_string(),
            }],
            domain_context: None,
        };

        assert!(dq.is_passthrough());
    }

    #[test]
    fn test_domain_context_serialization() {
        let ctx = DomainContext {
            table_name: "Policies".to_string(),
            description: Some("Insurance docs".to_string()),
            vocab_hints: vec!["IBR".to_string(), "PDS".to_string()],
        };

        let json = serde_json::to_string(&ctx).unwrap();
        let restored: DomainContext = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.table_name, ctx.table_name);
        assert_eq!(restored.vocab_hints, ctx.vocab_hints);
        assert_eq!(restored.description, ctx.description);
    }
}
