//! Query trace types for audit and observability
//!
//! Every REASON query produces a `QueryTrace` that captures the full
//! retrieval process across all pipeline phases, including query decomposition,
//! BM25 candidate selection, structural filtering, LLM ranking, and beam search.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ==================== Core Trace ====================

/// Complete audit record for a single REASON query execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryTrace {
    /// Unique identifier for this trace
    pub trace_id: String,
    /// The original user query
    pub query: String,
    /// Table ID this query was run against
    pub table_id: String,
    /// When the query was executed
    pub created_at: DateTime<Utc>,
    /// Total wall-clock duration in milliseconds
    pub duration_ms: u64,
    /// Phase 0 — query decomposition (if performed)
    pub decomposition: Option<DecompositionTrace>,
    /// BM25 candidate selection
    pub bm25_selection: Bm25SelectionTrace,
    /// Tree-grep structural filter
    pub structural_filter: StructuralFilterTrace,
    /// LLM summary ranking
    pub llm_ranking: LlmRankingTrace,
    /// Beam search deep reasoning
    pub beam_reasoning: BeamReasoningTrace,
    /// Final results returned to the caller
    pub final_results: Vec<FinalResultTrace>,
}

// ==================== Phase 0: Decomposition ====================

/// Trace data captured during query decomposition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecompositionTrace {
    /// Domain context used (if any)
    pub domain_context: Option<DomainContextTrace>,
    /// Sub-queries generated by the LLM
    pub sub_queries: Vec<SubQueryTrace>,
}

/// The domain context that was provided to the decomposer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DomainContextTrace {
    /// Name of the table
    pub table_name: String,
    /// Table description
    pub description: Option<String>,
    /// Domain vocabulary hints from table metadata
    pub vocab_hints: Vec<String>,
}

/// A single sub-query produced by the decomposer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubQueryTrace {
    /// The expanded search query text
    pub text: String,
    /// LLM's rationale for this sub-query
    pub rationale: String,
    /// Number of BM25 candidate documents this sub-query produced
    pub bm25_hits: usize,
}

// ==================== BM25 Selection ====================

/// Trace data from the BM25 candidate selection phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Bm25SelectionTrace {
    /// Total unique candidates after deduplication across all sub-queries
    pub total_candidates: usize,
    /// Top-level BM25 hits per document
    pub hits: Vec<Bm25HitTrace>,
}

/// A single document hit from BM25 search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Bm25HitTrace {
    pub document_id: String,
    pub document_title: String,
    /// Best BM25 score across all matched nodes in this document
    pub score: f32,
    /// Number of nodes in this document that matched query terms
    pub matched_node_count: usize,
    /// Sub-query that produced this hit (index into decomposition.sub_queries)
    pub sub_query_index: usize,
}

// ==================== Structural Filter ====================

/// Trace data from the structural tree-grep filter phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StructuralFilterTrace {
    /// Search terms extracted from the query
    pub terms: Vec<String>,
    /// Count of documents remaining after filtering
    pub filtered_count: usize,
    /// Per-document structural scores
    pub scores: Vec<TreeGrepScoreTrace>,
}

/// Structural score assigned to a document by tree-grep.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeGrepScoreTrace {
    pub document_id: String,
    pub document_title: String,
    /// Combined BM25 + structural score
    pub combined_score: f32,
    /// Section titles that matched query terms structurally
    pub matched_sections: Vec<String>,
}

// ==================== LLM Ranking ====================

/// Trace data from the LLM summary ranking phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmRankingTrace {
    /// Number of documents input to this phase
    pub input_count: usize,
    /// Number of documents selected after ranking
    pub selected_count: usize,
    /// Whether the LLM ranking step was skipped (too few candidates)
    pub skipped_llm: bool,
    /// LLM-assigned rankings
    pub rankings: Vec<DocumentRankingTrace>,
}

/// LLM relevance ranking for a single document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DocumentRankingTrace {
    pub document_id: String,
    pub document_title: String,
    /// Relevance score (0.0–1.0) assigned by LLM
    pub relevance: f32,
    /// LLM's brief reasoning for the score
    pub reasoning: String,
}

// ==================== Beam Reasoning ====================

/// Trace data from the LLM beam-search deep reasoning phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeamReasoningTrace {
    /// Number of documents processed
    pub documents_processed: usize,
    /// Total LLM calls across all documents
    pub total_llm_calls: usize,
    /// Per-document beam traversal data
    pub documents: Vec<BeamDocumentTrace>,
}

/// Beam-search traversal trace for a single document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeamDocumentTrace {
    pub document_id: String,
    pub document_title: String,
    /// Total nodes visited during traversal
    pub nodes_visited: usize,
    /// Nodes pruned (not explored)
    pub nodes_pruned: usize,
    /// LLM calls made for this document
    pub llm_calls: usize,
    /// Leaf nodes that were verified as relevant
    pub relevant_leaves: Vec<LeafVerificationTrace>,
}

/// A leaf node verified by the LLM during beam search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeafVerificationTrace {
    pub node_id: String,
    pub node_title: String,
    /// Whether the LLM judged this node as relevant
    pub is_relevant: bool,
    /// Confidence score (0.0–1.0)
    pub confidence: f32,
    /// Path from document root to this leaf
    pub path: Vec<String>,
    /// Reasoning steps taken to reach this leaf (LLM decisions at each branch)
    pub reasoning_steps: Vec<BeamReasoningStep>,
}

/// A single LLM navigation decision made during beam traversal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeamReasoningStep {
    /// Title of the node at which the decision was made
    pub node_title: String,
    /// LLM reasoning for choosing this branch
    pub decision: String,
    /// Confidence at this step
    pub confidence: f32,
}

// ==================== Final Results ====================

/// One document chunk returned as a final query result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalResultTrace {
    pub document_id: String,
    pub document_title: String,
    pub node_id: String,
    pub node_title: String,
    /// Final confidence score
    pub confidence: f32,
    /// Path from document root to this node
    pub path: Vec<String>,
}

// ==================== Summary (for listing) ====================

/// Compact summary of a QueryTrace used when listing traces.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryTraceSummary {
    pub trace_id: String,
    pub query: String,
    pub table_id: String,
    pub created_at: DateTime<Utc>,
    pub duration_ms: u64,
    /// Number of final results returned
    pub result_count: usize,
    /// Number of sub-queries generated (0 = no decomposition)
    pub sub_query_count: usize,
    /// Total LLM calls across all phases
    pub total_llm_calls: usize,
    /// Number of BM25 candidates in phase 1
    pub candidate_count: usize,
}

impl From<QueryTrace> for QueryTraceSummary {
    fn from(t: QueryTrace) -> Self {
        QueryTraceSummary::from(&t)
    }
}

impl From<&QueryTrace> for QueryTraceSummary {
    fn from(t: &QueryTrace) -> Self {
        Self {
            trace_id: t.trace_id.clone(),
            query: t.query.clone(),
            table_id: t.table_id.clone(),
            created_at: t.created_at,
            duration_ms: t.duration_ms,
            result_count: t.final_results.len(),
            sub_query_count: t
                .decomposition
                .as_ref()
                .map(|d| d.sub_queries.len())
                .unwrap_or(0),
            total_llm_calls: t.beam_reasoning.total_llm_calls + 1, // +1 for llm_ranking
            candidate_count: t.bm25_selection.total_candidates,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_trace(
        trace_id: &str,
        table_id: &str,
        sub_query_count: usize,
        beam_llm_calls: usize,
        candidates: usize,
        results: usize,
    ) -> QueryTrace {
        QueryTrace {
            trace_id: trace_id.to_string(),
            query: "test query".to_string(),
            table_id: table_id.to_string(),
            created_at: DateTime::from_timestamp(1_700_000_000, 0).unwrap(),
            duration_ms: 42,
            decomposition: if sub_query_count > 0 {
                Some(DecompositionTrace {
                    domain_context: None,
                    sub_queries: (0..sub_query_count)
                        .map(|i| SubQueryTrace {
                            text: format!("sub query {i}"),
                            rationale: "rationale".to_string(),
                            bm25_hits: 3,
                        })
                        .collect(),
                })
            } else {
                None
            },
            bm25_selection: Bm25SelectionTrace {
                total_candidates: candidates,
                hits: vec![],
            },
            structural_filter: StructuralFilterTrace {
                terms: vec![],
                filtered_count: 0,
                scores: vec![],
            },
            llm_ranking: LlmRankingTrace {
                input_count: 0,
                selected_count: 0,
                skipped_llm: false,
                rankings: vec![],
            },
            beam_reasoning: BeamReasoningTrace {
                documents_processed: 0,
                total_llm_calls: beam_llm_calls,
                documents: vec![],
            },
            final_results: (0..results)
                .map(|i| FinalResultTrace {
                    document_id: format!("doc_{i}"),
                    document_title: format!("Doc {i}"),
                    node_id: format!("node_{i}"),
                    node_title: format!("Node {i}"),
                    confidence: 0.9,
                    path: vec![],
                })
                .collect(),
        }
    }

    #[test]
    fn test_query_trace_summary_from() {
        let trace = make_trace("tr-1", "tbl-1", 3, 5, 10, 2);
        let summary = QueryTraceSummary::from(&trace);

        assert_eq!(summary.trace_id, "tr-1");
        assert_eq!(summary.table_id, "tbl-1");
        assert_eq!(summary.result_count, 2);
        assert_eq!(summary.sub_query_count, 3);
        assert_eq!(summary.candidate_count, 10);
        // beam_reasoning.total_llm_calls (5) + 1 for llm_ranking phase
        assert_eq!(summary.total_llm_calls, 6);
        assert_eq!(summary.duration_ms, 42);
    }

    #[test]
    fn test_summary_no_decomposition() {
        let trace = make_trace("tr-2", "tbl-1", 0, 0, 0, 0);
        let summary = QueryTraceSummary::from(&trace);
        assert_eq!(summary.sub_query_count, 0);
    }

    #[test]
    fn test_query_trace_serialization_round_trip() {
        let trace = make_trace("tr-3", "tbl-2", 2, 4, 8, 3);
        let json = serde_json::to_string(&trace).expect("serialization failed");
        let restored: QueryTrace = serde_json::from_str(&json).expect("deserialization failed");

        assert_eq!(restored.trace_id, trace.trace_id);
        assert_eq!(restored.query, trace.query);
        assert_eq!(restored.duration_ms, trace.duration_ms);
        assert_eq!(restored.bm25_selection.total_candidates, 8);
        assert_eq!(restored.beam_reasoning.total_llm_calls, 4);
        assert_eq!(restored.final_results.len(), 3);
        assert_eq!(
            restored.decomposition.as_ref().map(|d| d.sub_queries.len()),
            Some(2)
        );
    }

    #[test]
    fn test_beam_reasoning_step_fields() {
        let step = BeamReasoningStep {
            node_title: "Section 3".to_string(),
            decision: "relevant to query".to_string(),
            confidence: 0.85,
        };
        assert_eq!(step.node_title, "Section 3");
        assert!((step.confidence - 0.85).abs() < f32::EPSILON);
    }
}
