name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "assets/**"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "assets/**"
      - "LICENSE"
      - ".gitignore"

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: ""
  SCCACHE_GHA_ENABLED: "false"
  CARGO_INCREMENTAL: 0

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  ci:
    name: Clippy + Test
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Clippy
        run: cargo clippy --workspace --exclude reasondb --all-targets -- -D warnings
        env:
          RUSTC_WRAPPER: ""
          RUSTFLAGS: -Dwarnings
      - name: Test
        run: cargo test --workspace --exclude reasondb
        env:
          RUSTC_WRAPPER: ""
